### PR TITLE
Feature/android variable integration

### PR DESCRIPTION
**Pull request by briancaw**

### CODE REVIEW

**Comment by robludwig** [comment]
Does this need to be merged for configuration using `cordova plugin add --variable` to work? For me using that syntax doesn't work on the master branch, but does work when I install the plugin from this branch.

**Comment by briancaw** [comment]
Hi @robludwig 

We modified the variables to namespace them per platform, so you should still be able to use --variable, but you have to adjust for the modified tokens...see https://github.com/Appboy/appboy-cordova-sdk/blob/master/sample-project/sync_plugin.sh#L2 for an example.

**Comment by robludwig** [comment]
Yikes, thanks for catching that. I'll read a little more closely next time...

**Comment by briancaw** [comment]
No worries; please let us know if you have any comments/questions/concerns/feature-requests for 2.0.0.  Thanks!

**Pull request closed without merging**
